### ISSUE TITLE
ValueError: No such layer: labels_out

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#11]
I'm getting the following error when running `SynthSeg.training.training`:

```
Traceback (most recent call last):
  File "/home/miran045/reine097/PycharmProjects/SynthSeg/scripts/SynthSeg_scripts/SynthSeg_training.py", line 44, in <module>
    model_dir=path_model_dir)
  File "/home/miran045/reine097/PycharmProjects/SynthSeg/SynthSeg/training.py", line 263, in training
    wl2_model = metrics.metrics_model(wl2_model, segmentation_labels, 'wl2')
  File "/home/miran045/reine097/PycharmProjects/SynthSeg/SynthSeg/metrics_model.py", line 21, in metrics_model
    labels_gt = input_model.get_layer('labels_out').output
  File "/home/miran045/reine097/.conda/envs/synthseg_msi/lib/python3.7/site-packages/keras/engine/network.py", line 365, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: labels_out
```
I'm using version 2.3.1 of `keras`.  I use the default arguments for all but the first two arguments of `SynthSeg.training.training`:

```
training(labels_dir=path_training_label_maps,
         model_dir=path_model_dir)
```

`path_training_label_maps` points to a directory containing NIFTI files with FreeSurfer segmentations.

**Comment by BBillot** [comment]
Hi Paul,
can you confirm you still have this error with the latest version of the code ?
I mean this code is obviously under development, so it's subject to errors, but I am not able to replicate the issue.
Also, I don't recommend using default parameters for training if you use FS segmentations. Indeed this will trigger the network to segment all available labels in your maps, including CSF, WM hypointensities, etc.
I think it's easier if you just send me an email at:
benjamin.billot.18@ucl.ac.uk

**Comment by BBillot** [comment]
OK, so I've managed to spot the error. It should work okay now. 

The error was triggered because you didn't provide a segmentation label list, which is totally fine, and leads to the network learning to segment ALL the labels present in your training label maps. Again this is totally fine, but it may not be optimal: while there are some structures/tissues/fluids that you must represent in the synthetic images, these may waste a lot of the network's learning capacity for not much if you're also trying to segment them (like the CSF, or the white matter hypointensities for example). Therefore, and based on my experience, I strongly suggest to segment only a subset of the FreeSurfer labels. Of course this also depends on what you're trying to achieve.
Anyway I hope this helps, and I'm going to close this issue for now.

Benjamin

PS: I'm working on something new, and there will be a lot of changes to the current version of SynthSeg soon-ish.
