### ISSUE TITLE
Tensorflow and keras issues

### ISSUE THREAD

**Issue by rb643** [BBillot/SynthSeg#12]
Seems there is some incompatibility with newer versions of tensorflow, to avoid the endless loop of up and downgrading tensorflow and keras any chance the general codebase could implement the suggested solution of replacing the keras import with the tf.keras import?

https://github.com/keras-team/keras/issues/14632

**Comment by BBillot** [comment]
Thanks for your suggestion, I'll look into it in the future. In the meantime, you can create a virtual environment and install all the libraries listed in requirement.txt, which also specifies the version of each library.
Closing this for now.
Benjamin

**Comment by atsuch** [comment]
I had exactly the same problem. 

The suggested solution does not seem to work anymore, since I could not find tensorflow-gpu=2.0.1 through conda or pip. With keras=2.3.1 used with the tensorflow-gpu=2.4.1 (which was installed when using conda install with -c anaconda), I get various errors related to keras vs tf.keras import...

I will see if the older version of tensorflow available through pip (>2.2.0) would work, but meantime, it would be nice to have import fixes...

**Comment by BBillot** [comment]
Hi, I've been working on replacing all keras import to tf.keras, but I haven't pushed this part yet (for various reasons... ).
Anyway, I'll let you know when I push this new commit ! :)
In the meantime, are you using python 3.6 ? (I forgot if I have it written somewhere in the README or in the requirements.) Because tensorflow-gpu=2.0.1 *is* available with this version.

**Comment by atsuch** [comment]
Yes, actually, I just tried creating a new environment again with Python 3.6 and managed to install keras=2.3.1 with tensorflow-gpu=2.0.1 as in the requirement.txt. Yay!

I just wanted to try the Synthseg_predict.py script, which seems to be working now. 

It would be nice to mention the python version requirement somewhere in the README for others like me...!

**Comment by BBillot** [comment]
Yes, will do !
Thanks for your feedback :)
