### ISSUE TITLE
Identical transformations for T1 and T2 images?

### ISSUE THREAD

**Issue by paul-reiners** [BBillot/SynthSeg#18]
This is a question, not an 'issue'.  When I create a T1 and T2 image as below:

```
        im, lab = brain_generator.generate_brain()
        t1_im = im[:, :, :, 0]
        t2_im = im[:, :, :, 1]
```
are the T1, T2, and labeled images consistent with each other?  For example, are they all positioned the same?  Or could the T1 and T2 differ slightly as when a person moves their head in the scanner in the middle of acquisition?

**Comment by BBillot** [comment]
Hi, the way we have it at the moment is: if you decide to generate multi-modality scans (e.g. T1-T2), then all the channels are perfectly aligned, as they are generated from the exact same label map. But if you are interested in synthesising mis-alignement between channels (due to head movements or mis-registrations), you can have a look at the SynthSR repo, where we do have this option:

https://github.com/BBillot/SynthSR/blob/944f723ee5a79e6e8dd310790cc269b74b68098a/SynthSR/labels_to_image_model.py#L202-L211
and
https://github.com/BBillot/SynthSR/blob/944f723ee5a79e6e8dd310790cc269b74b68098a/SynthSR/labels_to_image_model.py#L231-L239
