### ISSUE TITLE
Input and output dimension mismatch 

### ISSUE THREAD

**Issue by nithyabsy** [BBillot/SynthSeg#30]
Hi, I have an input data of size 256x256x128 and tried to generate segmentation results as per the commands given in the Readme file.
When I ran the code, output size is 240x240x192 and there is mismatch between input and output size.

Here is the command i used for generating results
python ./scripts/commands/SynthSeg_predict.py --i ./data/inputs/2/anat.nii --o ./data/outputs/anat2_seg.nii

Here is link for the input data and looks like it's a raw data without any pre-processing step
https://escholarship.umassmed.edu/cs_schizbull08/

Is dimension mismatch comes only with raw data?? In this case, how can we overlay output segmentation maps on data ??
 
Can you please let me know if i missed anything here..

Thanks..

**Comment by BBillot** [comment]
If the output is not the same size as the input, this is probably due to the fact that your data is not at 1mm isotropic resolution.

Indeed, if it's not at 1mm, then the input images are automatically resampled to 1mm, in order to match the resolution at which the network was trained. 

The outputs are given at 1mm, no matter what. If you do not use a resolution-aware image viewer, that would result in images/outputs that do not match. So I recommand to use a viewer like FreeView (shipped with FreeSurfer). Another (simpler) solution is to use the "--resample" flag when running the command. This flag will enable you to save the internally resampled images, such that you can view the output segmentation on top of the image. More explanations on how to use this flag are given in the README.

Best,
Benjamin
