### ISSUE TITLE
Robustness of SynthSeg on MRIs having large lesions (stroke, tumor, etc)

### ISSUE THREAD

**Issue by saruarlive** [BBillot/SynthSeg#37]
How robust/precise is the SynthSeg on MRIs having large lesions (stroke, tumor, etc)? Could you tell bit more about it?

**Comment by BBillot** [comment]
SynthSeg has been trained to segment lesions (MS, stroke, etc.) as the structure that is underneath. Essentially it means that SynthSeg has been trained to ignore lesions, since these are extremely complicated to robustly segment.

On the other hand, SynthSeg has not been trained to deal with large tumours, but it is still robust to small ones.

So globally, I'd say that if you wish to specifically segment lesions/tumours SynthSeg is not the tool you're looking for, but if you're interested in whole-brain segmentation with robustness to lesions/tumours then you should definitely give SynthSeg a try !
