### ISSUE TITLE
Is the WML segmentation model available?

### ISSUE THREAD

**Issue by PeterMcGor** [BBillot/SynthSeg#43]
Dear @BBillot, 

Thanks for sharing the code. 

I discovered the SynthSeg model applied to MS lesions but the model included in the repo corresponds to the referred main paper. Is the WML segmentation model available as well?

**Comment by BBillot** [comment]
Hello,
thanks for the interest!

Unfortunately the model that segments white matter lesions with a dedicated label is not available. This is because this paper was written before we developed the resolution-agnostic model. This means that the white matter lesion network has to be retrained for every new resolution. In other words, we would need to distribute a new model for every resolution, which is not practical at all.

Instead, we here distribute the latest model of SynthSeg (version 2.0), which is robust to a wide range of MRI contrasts and resolutions, so it doesn't need any retraining. We emphasise that despite SynthSeg 2.0 doesn't segment white matter lesion directly, it is still robust to them. This means that the output segmentations do not have a dedicated label for lesions, which are instead segmented as their underlying structure (ie. a lesion in white matter will be segmented as white matter, see the examples in the first picture of the readme file).

If you're specifically interested in segmentation of WML, then I understand that SynthSeg 2.0 is not very useful for you. Several people are now working to extend the resolution- and contrast-agnostic model to lesions and tumours, but it's a long process, and I'm not sure when this will be available.

Hope this helps,
Benjamin

**Comment by PeterMcGor** [comment]
Hi Benjamin, 
Sorry for the delayed response.

I understand. Let's see if I can build something from your resolution-contrast agnostic approach. 
Cheers!
