### ISSUE TITLE
v2 model file missing from repository

### ISSUE THREAD

**Issue by jhlegarreta** [BBillot/SynthSeg#62]
Thanks for having developed and making available this tool.

Unless the optional `--v1` flag is specified, the [tutorial command](https://github.com/BBillot/SynthSeg/blob/master/README.md?plain=1#L84) raises an exception since it is unable to find the v2 model file, as it does not exist in the repository.

The docker file referenced in #36 is not available, or cannot be found openly under the `hippocampusgirl` username in Docker Hub. Is there any possibility to add the file to the repository?

Thanks.

**Comment by BBillot** [comment]
Hi and thanks for the interest! :)

I think you missed the installation section of the README where I give a minimal command to install the required libraries and I give a link to download the different v2 models that are not directly included in this repo for memory constraints. 

Hope this helps,
Benjamin

PS: the v1 model could fit memory-wise in the repo, that's why you could use it without having to download it first.

**Comment by jhlegarreta** [comment]
Ah, missed the v2 model bit; my bad. Thanks Benjamin and sorry for the extra work taken to respond to the question.
