### ISSUE TITLE
 Segmentation Discrepancies Analysis

### ISSUE THREAD

**Issue by NasrinPrenuvo** [BBillot/SynthSeg#76]
I was curious if you conducted a test-retest analysis comparing the segmentation outputs of FreeSurfer and SynthSeg. In my examination of one subject, the results for cortical sub-volumes were unsatisfactory, showing a significant percentage of volume changes between the two methods. Contrary to my expectations, I anticipated a closer agreement between the two methods. I am particularly interested in understanding the performance of the two methods about subcortical regions.

**Comment by BBillot** [comment]
Hi, 
SynthSeg was trained on FreeSurfer segmentations for cortical parcellation, so ideally they should be pretty much alike, but there is no guarantee. I guess the question is what type of images are you using ? if 1mm T1 scans, then you should definitely go for FreeSurfer

**Comment by NasrinPrenuvo** [comment]
Prior to employing SynthSeg, I utilized MRI Convert with the "--conform" option to resample my image to a 1mm resolution. then, I conducted tests using both SynthSeg and FreeSurfer on a resampled image. Upon comparing the results, a notable volume difference was observed for the majority of cortical regions of interest (ROIs) between the outputs of SynthSeg and FreeSurfer.

**Comment by BBillot** [comment]
Yes, there is no guarantee that SynthSeg and FreeSurfer will give you the same result, as we do not have any mechanism to check between the two. It's just that SynthSeg was trained on FreeSurfer cortical parcellations, but that's as far as the resemblance goes.

But what's the resolution of your images ? if it's anything different than 1mm isotropic, FreeSurfer should not be trusted. As a rule of thumb for cortical analysis, if your images are 1mm T1s, use FreeSurfer, otherwise, use SynthSeg.

Also, I understand that you resampled the images externally, so that FreeSurfer and SynthSeg have the exact same inputs, but just wanted to highlight (mainly for other readers) that when only using SynthSeg, the resampling is done internally, so no need to use mri_convert beforehand.

In any case, I strongly suggest to perform a visual quality assessment of the results for cortical parcellation.

Best
Benjamin
