### ISSUE TITLE
Force resampling

### ISSUE THREAD

**Issue by loneblues** [BBillot/SynthSeg#86]
Is there a way to force resampling to 1-mm isotropic resolution, even if the resolution is close to 1-mm isotropic and resampling is skipped internally? 
Also, is the output resampled image bias corrected in any way?

Thanks!

**Comment by BBillot** [comment]
Ohlala, I'm so sorry, this question completely escaped my attention!

So the resampled image are NOT corrected for bias, because SynthSeg has been trained to handle bias-corrupted images.

Then if you wish to ALWAYS resample images at 1mm isotropic, you can simply replace L449 of SynthSeg/predict_synthseg.py ([here](https://github.com/BBillot/SynthSeg/blob/2a2aa3bbfccb83f8253a51ca8b329b9938a2646d/SynthSeg/predict_synthseg.py#L449C5-L449C76)) by:

`if True:`

Hope this helps and sorry again for the late answer,
Benjamin
