### ISSUE TITLE
failed to predict on CPU

### ISSUE THREAD

**Issue by Neglecteder** [BBillot/SynthSeg#88]
I use `python ./scripts/commands/SynthSeg_predict.py --i .\mri.nii --o .\mriSeg.nii --fast --cpu` to infer.
I don't get any errors, but I don't get any results either.
![image](https://github.com/user-attachments/assets/f9146e56-4075-4407-8ead-dc165ad85abe)
I don't know why, is it my command problem?
My video memory is only 6G, which cannot meet the requirements, so I can only use CPU

**Comment by BBillot** [comment]
Hi, I think this is because you run out of memory. You have several options there.

1. First I wouldn't use --threads 2, this uses waayyy more memory than --threads 1 (default). I'm pretty sure this will fix the issue.
2. Then, if it still doesn't work, you can use the --crop flag. I don't know the field of view of your image, but decreasing its size is always a good option when running out of memory. But of course, be careful not too crop too much, otherwise you will not segment the entire image.

**Comment by Neglecteder** [comment]
> Hi, I think this is because you run out of memory. You have several options there.
> 
> 1. First I wouldn't use --threads 2, this uses waayyy more memory than --threads 1 (default). I'm pretty sure this will fix the issue.
> 2. Then, if it still doesn't work, you can use the --crop flag. I don't know the field of view of your image, but decreasing its size is always a good option when running out of memory. But of course, be careful not too crop too much, otherwise you will not segment the entire image.

Thank you for your answer
I have tried the parameter combination you mentioned before, but it didn't work as expected. Maybe I should increase the memory or change the graphics card, which is the best solution. 
(╥_╥)
