### ISSUE TITLE
[question] which modality should I use to get the best results?

### ISSUE THREAD

**Issue by neuronflow** [BBillot/SynthSeg#96]
I have a brain tumor dataset with multiple modalities.
* T1
* T1c
* T2
* T2-FLAIR

Usually, T1c has the highest spatial resolution. Which modality promises the best results?

Can I supply multiple modalities, so SynthSeg can exploit all the information available?

**Comment by hvgazula** [comment]
@BBillot might be able to provide better insights. Nevertheless, synthseg is contrast-agnostic and doesn't have a feature to account for multiple modalities in one go.

**Comment by BBillot** [comment]
Hi, even though SynthSeg is robust to a large range of contrasts and resolutions, it tends to perform better on T1 scans (that's the modality with best white/grey matter contrast, that's why it's so widely used in brain exams). But overall I'd say use the modality with highest resolution (which is T1c in your case).

Multi-modality is not supported at the moment.

But please be aware that SynthSeg doesn't segment tumours and is has not been trained to be robust to large tumours. Small tumours are okay, but the bigger they get the more likely SynthSeg is to fail. This may bias your results.

Hope this helps,
Benjamin
